[package]

name = "playback-sdl2"
version = "0.0.1"
authors = ["Dan Spencer <dan@atomicpotato.net>"]

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
getopts = "0.2.*"

[dependencies.libxm]
path = "../.."

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
